# Generated by Django 5.0 on 2023-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='color',
            field=models.CharField(default='62, 202, 24', max_length=13),
        ),
    ]
