# Generated by Django 5.0 on 2023-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_alter_queue_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='color',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
